#!/bin/bash

docker push netsil/servicesim:latest

docker tag netsil/servicesim netsil/servicesim:alpha
docker tag netsil/servicesim netsil/servicesim:beta
docker tag netsil/servicesim netsil/servicesim:delta
docker tag netsil/servicesim netsil/servicesim:gamma
docker tag netsil/servicesim netsil/servicesim:kappa
docker tag netsil/servicesim netsil/servicesim:lambda
docker tag netsil/servicesim netsil/servicesim:mu
docker tag netsil/servicesim netsil/servicesim:omicron
docker tag netsil/servicesim netsil/servicesim:theta
docker tag netsil/servicesim netsil/servicesim:eta
docker tag netsil/servicesim netsil/servicesim:eta-v2
docker tag netsil/servicesim netsil/servicesim:zeta
docker tag netsil/servicesim netsil/servicesim:iota
docker tag netsil/servicesim netsil/servicesim:pi
docker tag netsil/servicesim netsil/servicesim:epsilon

docker push netsil/servicesim:alpha
docker push netsil/servicesim:beta
docker push netsil/servicesim:delta
docker push netsil/servicesim:gamma
docker push netsil/servicesim:kappa
docker push netsil/servicesim:lambda
docker push netsil/servicesim:mu
docker push netsil/servicesim:omicron
docker push netsil/servicesim:theta
docker push netsil/servicesim:eta
docker push netsil/servicesim:eta-v2
docker push netsil/servicesim:zeta
docker push netsil/servicesim:iota
docker push netsil/servicesim:pi
docker push netsil/servicesim:epsilon

